### ISSUE TITLE
JOSS review

### ISSUE THREAD

**Issue by amoeba** [prabhuramachandran/vixen#23]
Hi @prabhuramachandran, I've just finished going through the review checklist over on https://github.com/openjournals/joss-reviews/issues/1501 and only had one item I couldn't check off:

- [x] Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

Could you please expand the "Support" section of the README to cover this?

Otherwise, everything else looks great. I found a few typographical errors that I'll send a PR for in a sec. Let me know if you have any questions and also let me know when you want me to look at the README again.

I found the software pretty straightforward to use but had one question: In the Project view, I tried to select multiple items and couldn't. Is there a way or could this be a useful thing to add? This question isn't strictly part of the review process so you don't need to answer it or do anything about it in order to finalize the review.

**Comment by amoeba** [comment]
PR I mentioned above is https://github.com/vixen-project/vixen/pull/24.

**Comment by prabhuramachandran** [comment]
Hi Bryce,

Thanks for the kind comments and your thorough review.  I will make the requested changes to the support section later today.  I have merged your kind PR! 

Multiple selection is a great idea and one we thought about but something I am not quite sure how best to implement.  Is this just to be able to edit multiple tags?  The issue is, what exactly should the UI do on a multi-selection of files, what about a directory?  If there are already existing fields, multi-selecting them would allow a user to accidentally edit tags when they may not have wanted to.  Also it isn't clear what the video view should do, showing multiple videos/pictures may be a bit too much?  Given the difficulties in what exactly would be ideal I just decided not to implement it until there was a clear idea of what exactly we wanted to do.  I hope that clarifies the reason why we don't have that feature (yet).

Anyway, thanks for the pointer to the support section needing work, I will add that later today.

Thanks again for taking the time to review ViXeN!

**Comment by amoeba** [comment]
Sounds like you've definitely scratched your head a bit on the multiple-selection idea and I agree it isn't straightforward. The use case I was thinking of would be to tag a set of files with the same tag and value, maybe just two files that are adjacent in the same folder or maybe an entire sub-folder of files. For example, if I was tagging site codes on a set of camera trap images and I had organized my images in subfolders by site, I could imagine wanting to tag a set of files all at once.

**Comment by prabhuramachandran** [comment]
Hi @amoeba,  

Thanks again for a specific use case.  This is a very useful idea indeed, we will keep this in mind for a subsequent release.  I have also expanded the support section a bit in #25.  In addition, I also just pushed a bug report template to make it easier for users to report problems and provide the necessary information.  I hope this is enough, please let me know if #25 is good enough and I can merge it, otherwise I will add to that PR with any suggestions you may have.

Thanks again!

**Comment by amoeba** [comment]
Looks great, thanks @prabhuramachandran 	! All set here.
